import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { StoreProvider } from "@/redux/StoreProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>
          {typeof metadata.title === "string"
            ? metadata.title
            : "Default Title"}
        </title>
        <meta
          name="description"
          content={metadata.description || "Default Description"}
        />
      </Head>
      <body className="text-white body-font uppercase ">
        <div className="bg-gray-900">
          <div className="container  mx-auto flex flex-wrap px-5 flex-col md:flex-row items-center md:justify-between">
            <div className="flex gap-5">
              <div className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
                <img
                  src="https://media3.giphy.com/media/dyFrL10k1eNm5tZIvU/giphy.gif?cid=6c09b952j9q69uyx8x2nelueto4bzfmj897aiebeudlz7en1&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=s"
                  alt="Logo"
                  height="80"
                  width="80"
                  object-fit="cover"
                />
              </div>
              <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
                <a href="/" className="mr-5 hover:text-gray-400">
                  Home
                </a>
                <a href="/about" className="mr-5 hover:text-gray-400">
                  About
                </a>

                <a href="/products" className="mr-5 hover:text-gray-400">
                  Products
                </a>
                <a href="/contact" className="mr-5 hover:text-gray-400">
                  Contact Us
                </a>
              </nav>
            </div>
            <div className="flex gap-5">
              <div className="inline-flex items-center  text-base mt-4 md:mt-0">
                ZALOGUJ
              </div>
              <div className="inline-flex items-center  text-base mt-4 md:mt-0">
                KOSZYK
              </div>
            </div>
          </div>
        </div>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
